### ISSUE TITLE
Other color for skipped Breakpoints

### ISSUE THREAD

**Issue by Chris2011** [Chris2011/nb-debugger-utils#6]
The tool works great, but I expect an other color for the breakpoints. The same happens in Chrome DevTools, when you skip the breakpoints, they got a brighter color, like a disabled state. If I have time, I will try to make a pull request.

Cheers

Chris

**Comment by markiewb** [comment]
That is not possible right now. In NB exists no special annotation (line highlighting) for muted breakpoints. Only for disabled breakpoints - see the screenshot. If it would exist then it would have been a editor color scheme issue and thus out of the scope of this plugin.

![2017-01-01_12h12_50](https://cloud.githubusercontent.com/assets/1857095/21580981/a038257e-d01b-11e6-9483-c8197a69a348.png)
